services:
    server:
        image: gushteradimityr/getting-started:latest
        ports:
            -   80:80
        environment:
            MYSQL_DATABASE: portal
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_HOST: mysql
        depends_on:
            -   mysql
        volumes:
            -   ./:/var/www/html
    mysql:
        image: mysql:latest
        ports:
            -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: portal
        volumes:
            -   portal:/var/lib/mysql
volumes:
    portal:
