version: "3.9"

services:
  microservice:
    container_name: microservice
    build: ./microservice
    volumes:
      - ./microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  favoritemicroservice:
    container_name: favoritemicroservice
    build: ./favoritemicroservice
    volumes:
      - ./favoritemicroservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  forummicroservice:
    container_name: forummicroservice
    build: ./forummicroservice
    volumes:
      - ./forummicroservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3020:3015"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  login-register-microservice:
    container_name: login-register-microservice
    build: ./login-register-microservice
    volumes:
      - ./login-register-microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "4001:4001"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  tipsmicroservice:
    container_name: tipsmicroservice
    build: ./tipsmicroservice
    volumes:
      - ./tipsmicroservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3016:3016"
    working_dir: /usr/src/app
    command: bash -c "npm install && node start.js"

  pantry-microservice:
    container_name: pantry-microservice
    build: ./pantry-microservice
    volumes:
      - ./pantry-microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "4010:4010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  shoppinglistmicroservice:
    container_name: shoppinglistmicroservice
    build: ./shoppinglistmicroservice
    volumes:
      - ./shoppinglistmicroservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "4053:4052"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm rebuild sqlite3 && npm run dev"

  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  msexample:
    driver: bridge
